# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.18.3

# Fabric API
fabric_version=0.114.1+1.21.3
#Cloth Config
cloth_version=16.0.143

#ModMenu
modmenu_version=12.0.0

#Hash of commit form which parallel gzip will be build
pgzip_commit_hash=af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6

# Mod Properties
mod_version = 3.1.4
maven_group = net.szum123321
archives_base_name = textile_backup